spring.application.name=pulseguard

server.port=8080

# MySQL configuration
spring.datasource.url=jdbc:mysql://localhost:3306/pulseguard_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root






# JPA configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Actuator configuration
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# Application information
management.info.env.enabled=true
info.app.name=PulseGuard
info.app.description=Website and API uptime monitoring system
info.app.version=1.0.2

# PulseGuard scheduler configuration
pulseguard.scheduler.enabled=false
pulseguard.scheduler.scan-delay-ms=10000
pulseguard.scheduler.initial-delay-ms=5000


