spring.application.name=pulseguard

server.port=8080

# MySQL running inside Docker
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://mysql:3306/pulseguard_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:pulseguard}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:pulseguard123}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

pulseguard.scheduler.enabled=true
pulseguard.scheduler.scan-delay-ms=10000
pulseguard.scheduler.initial-delay-ms=5000